import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useSession } from '@supabase/auth-helpers-react'
// import posts from '../data.json'
import {
  TbArrowBigUp,
  TbArrowBigUpFilled,
  TbArrowBigDown,
  TbArrowBigDownFilled,
} from 'react-icons/tb'
import { GoComment } from 'react-icons/go'
import Link from 'next/link'
import { supabase } from '@/lib/supabaseClient'
import { formatTimeAgo } from '@/utils'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps = async () => {
  let { data: posts } = await supabase.from('posts').select(`
    *, profiles(*)
  `)
  console.log(posts)

  return {
    props: { posts },
  }
}

export default function Home({ posts }) {
  const session = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`px-3 ${inter.className}`}>
        <div className='max-w-4xl mx-auto mt-5'>
          {session && (
            <Link
              className='inline-block text-blue-600 hover:underline mb-3'
              href='/create-post'
            >
              + Post something
            </Link>
          )}
          {posts.map((post, i) => {
            return <Post key={i} {...post} />
          })}
        </div>
      </main>
    </>
  )
}

function Post({
  id,
  profiles,
  title,
  subreddit,
  upvotes,
  comments,
  created_at,
}) {
  const relativeTime = formatTimeAgo(new Date(created_at))
  return (
    <Link href={`/post/${id}`}>
      <article className='flex bg-white rounded-md mb-1 border border-neutral-300 hover:border-neutral-500 cursor-pointer overflow-hidden'>
        <div className='flex flex-col font-bold text-sm bg-neutral-50 p-3'>
          <TbArrowBigUp size={25} />
          <div>{upvotes}</div>
          <TbArrowBigDown size={25} />
        </div>
        <div className='p-3 space-y-1'>
          <div className='flex text-sm gap-2'>
            {/* <div className='font-semibold hover:underline'>r/{subreddit}</div> */}
            <div className='text-neutral-500 font-extralight'>
              Posted by u/{profiles.username} {relativeTime}
            </div>
          </div>
          <h2 className='text-lg font-semibold'>{title}</h2>
          {/* <div className='inline-flex items-center gap-1 text-neutral-500 font-semibold text-sm hover:underline'>
            <GoComment size={15} /> {comments.length} comments
          </div> */}
        </div>
      </article>
    </Link>
  )
}
