import Head from 'next/head'
import { Inter } from 'next/font/google'
import posts from '../data.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={inter.className}>
        {posts.map((post, i) => {
          return <Post key={i} {...post} />
        })}
      </main>
    </>
  )
}

function Post({ postedBy, title, subreddit, upvotes, comments }) {
  return (
    <article className='flex'>
      <div>{upvotes}</div>
      <div>
        <div>Posted by u/{postedBy}</div>
        <div>{title}</div>
        <div>{comments.length} comments</div>
      </div>
    </article>
  )
}
